version: "3"
services:
    adguard-vpn-cli:
        image: supersunho/adguardvpn-cli:latest
        restart: unless-stopped
        container_name: adguard-vpn-cli
        env_file: .env
        environment:
            - PUID=${PUID:-1001}
            - PGID=${PGID:-1001}
        volumes:
            - ./data:/home/appuser/.local/share/adguardvpn-cli
        healthcheck:
            test: ["CMD-SHELL", "adguardvpn-cli status >/dev/null 2>&1 || exit 1"]
            interval: 1m
            timeout: 10s
            retries: 2
            start_period: 30s
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 6089:6089
            - 6881:6881
            - 6881:6881/udp
